# This file is generated by Makefile, please do not modify it directly.
PO :=
HTMLDIRSYSV_fr := html-fr-sysv
HTMLDIRSYSD_fr := html-fr-systemd
HTMLTARSYSV_fr := BLFS-SYSV-BOOK-$(MILESTONE)-fr-HTML.tar.bz2
HTMLTARSYSD_fr := BLFS-SYSD-BOOK-$(MILESTONE)-fr-HTML.tar.bz2
PDFSYSV_fr := BLFS-SYSV-BOOK-$(MILESTONE)-fr.pdf
PDFSYSD_fr := BLFS-SYSD-BOOK-$(MILESTONE)-fr.pdf
EPUBSYSV_fr := BLFS-SYSV-BOOK-$(MILESTONE)-fr.epub
EPUBSYSD_fr := BLFS-SYSD-BOOK-$(MILESTONE)-fr.epub

XML_fr := \
    $(shell find $(ORIGDIR) -name '*.xml' -a -type f \
	-o -name archive -prune -a -type f \
	-o -name stylesheets -prune -a -type f \
	-o -name template -prune -a -type f \
	| sed "s|$(ORIGDIR)/|blfsgen-fr/|g" | tr '\n' ' ')
PO_fr := \
    $(shell find $(ORIGDIR) -name '*.xml' -a -type f \
	-o -name archive -prune -a -type f \
	-o -name stylesheets -prune -a -type f \
	-o -name template -prune -a -type f \
	| sed "s|$(ORIGDIR)/|fr/|g" | sed 's|.xml$$|.po|' | tr '\n' ' ')
PO += $(PO_fr)
IMAGES_fr := $(shell find images -type f | sed "s|^|blfsgen-fr/|g" | tr '\n' ' ')
STYLESHEETS_fr := $(shell find stylesheets -type f | sed "s|^|blfsgen-fr/|g" | tr '\n' ' ')
COPY_fr := $(addprefix blfsgen-fr/,$(filestoget))

blfsgen-fr/%.xml: $(ORIGDIR)/%.xml fr/%.po sed_fr.sh
	mkdir -p $$(dirname $@)
	LANG=$(LANG_fr) po4a-translate -k 0 -f docbook -m $< -l $@.tmp -p $(word 2,$^) -M UTF-8 -L UTF-8
	./$(word 3,$^) $@.tmp
	sed '0,/#-#/s|\([^>]*\) #-# \([^<]*\)|\1|' -i $@.tmp
	sed '0,/#-#/s|\([^>]*\) #-# \([^<]*\)|\2|' -i $@.tmp
	sed -e 's|encoding="ISO-8859-1"|encoding="UTF-8"|g' -i $@.tmp
	sed -e 's|encoding="""|encoding="UTF-8"|g' -i $@.tmp
	mv $@.tmp $@

blfsgen-fr/images/%: images/%
	mkdir -p $$(dirname $@)
	@rm -f $@
	cp $< $@

blfsgen-fr/stylesheets/%: stylesheets/%
	mkdir -p $$(dirname $@)
	@rm -f $@
	@if [ "$(DOCBOOK_LOCATION)" = "" ]; then \
	  echo "DOCBOOK_LOCATION not set. Please set it in config.mk" ;\
	  false ;\
	fi
	sed -e 's|DOCBOOK_LOCATION|$(DOCBOOK_LOCATION)|g' $< > $@

fr/%.po: $(ORIGDIR)/%.xml
	mkdir -p $$(dirname $@)
	LANG=$(LANG_fr) po4a-updatepo -f docbook -m $< -p $@ -M UTF-8
	python3 set-xml.py $@
	@touch $@

clean-gen-fr:
	rm -rf blfsgen-fr

clean-product-fr:
	rm -rf $(HTMLTARSYSV_fr)
	rm -rf $(HTMLTARSYSD_fr)
	rm -rf $(HTMLDIRSYSV_fr)
	rm -rf $(HTMLDIRSYSD_fr)
	rm -rf $(PDFSYSV_fr)
	rm -rf $(PDFSYSD_fr)
	rm -rf $(EPUBSYSV_fr)
	rm -rf $(EPUBSYSD_fr)

.SECONDEXPANSION:
$(addprefix blfsgen-fr/,$(filestocopy)): INPUT=$(ORIGDIR)$(subst blfsgen-fr,,$@)
$(addprefix blfsgen-fr/,$(filestocopy)): $$(INPUT)
	mkdir -p $$(dirname $@)
	if [ -f $< ]; then cp $< $@; else cp -r $< $$(dirname $@); fi

genhtml-fr-sysv: $(XML_fr) $(COPY_fr) $(IMAGES_fr) $(STYLESHEETS_fr)
	LANG=$(LANG_fr) make -C blfsgen-fr -j1 REV=sysv BASEDIR=../$(HTMLDIRSYSV_fr) html

genhtml-fr-sysd: $(XML_fr) $(COPY_fr) $(IMAGES_fr) $(STYLESHEETS_fr)
	LANG=$(LANG_fr) make -C blfsgen-fr -j1 REV=systemd BASEDIR=../$(HTMLDIRSYSD_fr) html

genpdf-fr-sysv: $(PDFSYSV_fr)

$(PDFSYSV_fr): $(XML_fr) $(COPY_fr) $(IMAGES_fr) $(STYLESHEETS_fr)
	LANG=$(LANG_fr) make -C blfsgen-fr -j1 REV=sysv BASEDIR=.. PDF_OUTPUT=$@ pdf

genpdf-fr-sysd: $(PDFSYSD_fr)

$(PDFSYSD_fr): $(XML_fr) $(COPY_fr) $(IMAGES_fr) $(STYLESHEETS_fr)
	LANG=$(LANG_fr) make -C blfsgen-fr -j1 REV=systemd BASEDIR=.. PDF_OUTPUT=$@ pdf

gentar-fr-sysv: $(HTMLTARSYSV_fr)
$(HTMLTARSYSV_fr): $(XML_fr) $(COPY_fr) $(IMAGES_fr) $(STYLESHEETS_fr) genhtml-fr-sysv
	rm -f $@
	tar cjf $@ $(HTMLDIRSYSV_fr)

gentar-fr-sysd: $(HTMLTARSYSD_fr)
$(HTMLTARSYSD_fr): $(XML_fr) $(COPY_fr) $(IMAGES_fr) $(STYLESHEETS_fr) genhtml-fr-sysd
	rm -f $@
	tar cjf $@ $(HTMLDIRSYSD_fr)

genepub-fr-sysv: $(EPUBSYSV_fr)
$(EPUBSYSV_fr): $(XML_fr) $(COPY_fr) $(IMAGES_fr) $(STYLESHEETS_fr)
	LANG=$(LANG_fr) make -C blfsgen-fr -j1 REV=sysv EPUB_OUTPUT=$@ epub

genepub-fr-sysd: $(EPUBSYSD_fr)
$(EPUBSYSD_fr): $(XML_fr) $(COPY_fr) $(IMAGES_fr) $(STYLESHEETS_fr)
	LANG=$(LANG_fr) make -C blfsgen-fr -j1 REV=systemd EPUB_OUTPUT=$@ epub

upload-fr-sysv: $(SSH_AGENT)
	cd $(HTMLDIRSYSV_fr) ;\
	rsync --progress --recursive * --chmod=g+rw,Dg+rwx $(USER)@www.linuxfromscratch.org:/srv/www/www.fr.linuxfromscratch.org/view/blfs-svn/ || true

upload-fr-sysd: $(SSH_AGENT)
	cd $(HTMLDIRSYSD_fr) ;\
	rsync --progress --recursive --chmod=g+rw,Dg+rwx * $(USER)@www.linuxfromscratch.org:/srv/www/www.fr.linuxfromscratch.org/view/blfs-systemd-svn/ || true
HTMLDIRSYSV_pt_BR := html-pt_BR-sysv
HTMLDIRSYSD_pt_BR := html-pt_BR-systemd
HTMLTARSYSV_pt_BR := BLFS-SYSV-BOOK-$(MILESTONE)-pt_BR-HTML.tar.bz2
HTMLTARSYSD_pt_BR := BLFS-SYSD-BOOK-$(MILESTONE)-pt_BR-HTML.tar.bz2
PDFSYSV_pt_BR := BLFS-SYSV-BOOK-$(MILESTONE)-pt_BR.pdf
PDFSYSD_pt_BR := BLFS-SYSD-BOOK-$(MILESTONE)-pt_BR.pdf
EPUBSYSV_pt_BR := BLFS-SYSV-BOOK-$(MILESTONE)-pt_BR.epub
EPUBSYSD_pt_BR := BLFS-SYSD-BOOK-$(MILESTONE)-pt_BR.epub

XML_pt_BR := \
    $(shell find $(ORIGDIR) -name '*.xml' -a -type f \
	-o -name archive -prune -a -type f \
	-o -name stylesheets -prune -a -type f \
	-o -name template -prune -a -type f \
	| sed "s|$(ORIGDIR)/|blfsgen-pt_BR/|g" | tr '\n' ' ')
PO_pt_BR := \
    $(shell find $(ORIGDIR) -name '*.xml' -a -type f \
	-o -name archive -prune -a -type f \
	-o -name stylesheets -prune -a -type f \
	-o -name template -prune -a -type f \
	| sed "s|$(ORIGDIR)/|pt_BR/|g" | sed 's|.xml$$|.po|' | tr '\n' ' ')
PO += $(PO_pt_BR)
IMAGES_pt_BR := $(shell find images -type f | sed "s|^|blfsgen-pt_BR/|g" | tr '\n' ' ')
STYLESHEETS_pt_BR := $(shell find stylesheets -type f | sed "s|^|blfsgen-pt_BR/|g" | tr '\n' ' ')
COPY_pt_BR := $(addprefix blfsgen-pt_BR/,$(filestoget))

blfsgen-pt_BR/%.xml: $(ORIGDIR)/%.xml pt_BR/%.po sed_pt_BR.sh
	mkdir -p $$(dirname $@)
	LANG=$(LANG_pt_BR) po4a-translate -k 0 -f docbook -m $< -l $@.tmp -p $(word 2,$^) -M UTF-8 -L UTF-8
	./$(word 3,$^) $@.tmp
	sed '0,/#-#/s|\([^>]*\) #-# \([^<]*\)|\1|' -i $@.tmp
	sed '0,/#-#/s|\([^>]*\) #-# \([^<]*\)|\2|' -i $@.tmp
	sed -e 's|encoding="ISO-8859-1"|encoding="UTF-8"|g' -i $@.tmp
	sed -e 's|encoding="""|encoding="UTF-8"|g' -i $@.tmp
	mv $@.tmp $@

blfsgen-pt_BR/images/%: images/%
	mkdir -p $$(dirname $@)
	@rm -f $@
	cp $< $@

blfsgen-pt_BR/stylesheets/%: stylesheets/%
	mkdir -p $$(dirname $@)
	@rm -f $@
	@if [ "$(DOCBOOK_LOCATION)" = "" ]; then \
	  echo "DOCBOOK_LOCATION not set. Please set it in config.mk" ;\
	  false ;\
	fi
	sed -e 's|DOCBOOK_LOCATION|$(DOCBOOK_LOCATION)|g' $< > $@

pt_BR/%.po: $(ORIGDIR)/%.xml
	mkdir -p $$(dirname $@)
	LANG=$(LANG_pt_BR) po4a-updatepo -f docbook -m $< -p $@ -M UTF-8
	python3 set-xml.py $@
	@touch $@

clean-gen-pt_BR:
	rm -rf blfsgen-pt_BR

clean-product-pt_BR:
	rm -rf $(HTMLTARSYSV_pt_BR)
	rm -rf $(HTMLTARSYSD_pt_BR)
	rm -rf $(HTMLDIRSYSV_pt_BR)
	rm -rf $(HTMLDIRSYSD_pt_BR)
	rm -rf $(PDFSYSV_pt_BR)
	rm -rf $(PDFSYSD_pt_BR)
	rm -rf $(EPUBSYSV_pt_BR)
	rm -rf $(EPUBSYSD_pt_BR)

.SECONDEXPANSION:
$(addprefix blfsgen-pt_BR/,$(filestocopy)): INPUT=$(ORIGDIR)$(subst blfsgen-pt_BR,,$@)
$(addprefix blfsgen-pt_BR/,$(filestocopy)): $$(INPUT)
	mkdir -p $$(dirname $@)
	if [ -f $< ]; then cp $< $@; else cp -r $< $$(dirname $@); fi

genhtml-pt_BR-sysv: $(XML_pt_BR) $(COPY_pt_BR) $(IMAGES_pt_BR) $(STYLESHEETS_pt_BR)
	LANG=$(LANG_pt_BR) make -C blfsgen-pt_BR -j1 REV=sysv BASEDIR=../$(HTMLDIRSYSV_pt_BR) html

genhtml-pt_BR-sysd: $(XML_pt_BR) $(COPY_pt_BR) $(IMAGES_pt_BR) $(STYLESHEETS_pt_BR)
	LANG=$(LANG_pt_BR) make -C blfsgen-pt_BR -j1 REV=systemd BASEDIR=../$(HTMLDIRSYSD_pt_BR) html

genpdf-pt_BR-sysv: $(PDFSYSV_pt_BR)

$(PDFSYSV_pt_BR): $(XML_pt_BR) $(COPY_pt_BR) $(IMAGES_pt_BR) $(STYLESHEETS_pt_BR)
	LANG=$(LANG_pt_BR) make -C blfsgen-pt_BR -j1 REV=sysv BASEDIR=.. PDF_OUTPUT=$@ pdf

genpdf-pt_BR-sysd: $(PDFSYSD_pt_BR)

$(PDFSYSD_pt_BR): $(XML_pt_BR) $(COPY_pt_BR) $(IMAGES_pt_BR) $(STYLESHEETS_pt_BR)
	LANG=$(LANG_pt_BR) make -C blfsgen-pt_BR -j1 REV=systemd BASEDIR=.. PDF_OUTPUT=$@ pdf

gentar-pt_BR-sysv: $(HTMLTARSYSV_pt_BR)
$(HTMLTARSYSV_pt_BR): $(XML_pt_BR) $(COPY_pt_BR) $(IMAGES_pt_BR) $(STYLESHEETS_pt_BR) genhtml-pt_BR-sysv
	rm -f $@
	tar cjf $@ $(HTMLDIRSYSV_pt_BR)

gentar-pt_BR-sysd: $(HTMLTARSYSD_pt_BR)
$(HTMLTARSYSD_pt_BR): $(XML_pt_BR) $(COPY_pt_BR) $(IMAGES_pt_BR) $(STYLESHEETS_pt_BR) genhtml-pt_BR-sysd
	rm -f $@
	tar cjf $@ $(HTMLDIRSYSD_pt_BR)

genepub-pt_BR-sysv: $(EPUBSYSV_pt_BR)
$(EPUBSYSV_pt_BR): $(XML_pt_BR) $(COPY_pt_BR) $(IMAGES_pt_BR) $(STYLESHEETS_pt_BR)
	LANG=$(LANG_pt_BR) make -C blfsgen-pt_BR -j1 REV=sysv EPUB_OUTPUT=$@ epub

genepub-pt_BR-sysd: $(EPUBSYSD_pt_BR)
$(EPUBSYSD_pt_BR): $(XML_pt_BR) $(COPY_pt_BR) $(IMAGES_pt_BR) $(STYLESHEETS_pt_BR)
	LANG=$(LANG_pt_BR) make -C blfsgen-pt_BR -j1 REV=systemd EPUB_OUTPUT=$@ epub

upload-pt_BR-sysv: $(SSH_AGENT)
	cd $(HTMLDIRSYSV_pt_BR) ;\
	rsync --progress --recursive * --chmod=g+rw,Dg+rwx $(USER)@www.linuxfromscratch.org:/srv/www/www.pt_BR.linuxfromscratch.org/view/blfs-svn/ || true

upload-pt_BR-sysd: $(SSH_AGENT)
	cd $(HTMLDIRSYSD_pt_BR) ;\
	rsync --progress --recursive --chmod=g+rw,Dg+rwx * $(USER)@www.linuxfromscratch.org:/srv/www/www.pt_BR.linuxfromscratch.org/view/blfs-systemd-svn/ || true
